### PR TITLE
Milestonetwo

### PR DESCRIPTION
**Pull request by cgcarlosg**
In this pull request we want to add Friendships with:
(Milestone 2)

Create friend requests.
See your friends requests.
See incoming requests.
Accept requests.
Decline requests.
See your friends.

### CODE REVIEW

**Comment by cgcarlosg** [comment]
Project has to be fork again due to some issues with my machine
and I had to start the project again
This is the second time I send the project
thanks

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @cgcarlosg. Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] In Friendship V2 when a friendship is confirmed, an additional row with reverse user-friend pair is created. Please review the next issues:
  - [ ] There is no visual feedback if the friend request is being generated. 
  - [ ] Once a friendship request has been sent the button should be disabled or hidden so the current_current user won't be able to send and generate repeated friendship requests to the same user.
  image
  - [ ] Once a friendship request has been accepted it should create a reverse user-friend friendship. Right now both users have to accept the invitation.
- [ ] In the `User` model `friendships_made` and `friendships_approved` are doing the same thing. I see that the id changes, but it's unnecessary and only is duplicating code. Please just leave one they should show for either, user, the same information. Fix the rest of the associations accordingly.
- [ ] `UsersController#index` should display all users with the `friend request` button next to users who are not their friends already. This also means that it has to disappear from users that are already friends with.
- [ ] TimeLine should only show current_user post and current_user friends.
image
image



### [OPTIONAL]  :yellow_circle:  

- [ ] Naming things is always tricky as they have to be explicit, meaningful, and descriptive, but also short, they also have to show intent, and should be Understand by every person that goes through our code. User better names for the associations and models:
  **Model**
  FriendRequest --> Friendship
  
  **Associations**
  friendships_made, friendships_approved --> confirmed_friendships
  friend_offers --> pending_friendships

  This also will maintain the code DRY / clean without duplication.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUESTED

Hey there @cgcarlosg :wave: :wave: , great job on working on this project it looks great. However, from the previous TSE, I saw you got feedback for v2 instead of v1. So I will give feedback based on v1 and here are the scenarios that are missing :arrow_down_small: 

- [ ]  User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ]  User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

That's all :smile: , kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] User should only see their posts and their friend's in the timeline. Right now even without a friendship, the timeline is showing all user's posts to any logged user.
- [ ] The button to request a friendship should be in the user's profile and in the all users view.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @cgcarlosg 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes  👇.
- [ ] There is an issue with migration locally with PG. Please run locally in another directory and fix the issue
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by cgcarlosg** [comment]
Hi.
In the readme instructions There is and instruction.  
Rails db:drop:all 
Rails db:create
Rails db:migrante
Before running the app.
With that it worked.
Please tell me of it works for you.
I submit the code review with that solution.
Thanks

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @cgcarlosg :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [ ] Please, make all the changes as requested by the previous TSE.
* [ ] On the users index page, the `Invite to Friendship` is returning an error but working fine on the users show page.
* [ ] After inviting a friend from the users show page, the `Invite to Friendship` button becomes `Pending` but still remains `Invite to Friendship` on users index page.
* [ ] A user who has been invited to friendship should be able to see the `Accept` or `Decline` button on the users index page, as well as users show page but none of the 2 pages reflect that. The friendship index is the only one that shows that. Even after I clicked accept, it still didn't reflect on the users index and show pages.

## Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project. and I am thrilled to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:


_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request merged**
